#!/bin/bash

id=$(tail -n 1 journal | awk '{print $1+1}')
today=$(date "+%Y-%m-%d")

read -p "date[default $today]: " d
if [ -z "$d" ]; then d=$today; fi

if [ -f .tmp ]; then rm .tmp; fi
touch .tmp
while :
do
	echo =======================
	cat -n $accounts
	read -p "account[e to exit]: " ac
	if [ $ac = "e" ]; then break; fi
	ac=$(cat $account_name | sed -n ${ac}p)
	read -p "ammount: " am
	read -p "comment: " cm
	echo -e "$id $d $ac $am $cm" >> .tmp
done

echo =======================
cat .tmp
echo =======================
read -p "save? [y/N]: " ans
case $ans in
	[yY]) cat .tmp >> journal;;
	*) rm .tmp && echo aborted;;
esac
