#!/bin/bash
# cash flow

SCRIPT_DIR=$(cd $(dirname $0); pwd)
# budgetファイルの並びのまま出力したかった

if [ $# = 0 ]; then
	cat -n budget | sort -k2 | join -a 1 -1 2 - status | sort -k2 -n | 
		awk '{printf "%s %d %d %d\n", $1, $3, $4, $3-$4}' 
elif [ $1 = -h ]; then
	cat -n budget | sort -k2 | join -a 1 -1 2 - status | sort -k2 -n | 
		awk '{printf "%s %\047d %\047d %\047d\n", $1, $3, $4, $3-$4}' | 
		column -t -R 2,3,4
fi
