#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)
# budgetファイルの並びのまま出力したかった

if [ $# = 0 ]; then
	awk '{print $1,NR,$2,$3}' spending_budget | sort | join -a 1 - status | sort -n -k 2 | awk '{printf "%s %d %d\n",$1,$3,$4}' | awk '{print $1,$2,$3,$2-$3}' 
elif [ $1 = -h ]; then
	nline=$(cat income_budget | wc -l)
	cat income_budget spending_budget | 
		awk '{print $1,NR,$2,$3}' | sort | 
		join -a 1 - status | sort -n -k 2 | 
		awk '{printf "%s %d %d\n",$1,$3,$4}' | 
		awk -v n=$nline \
			'NR<=n{printf "%s %\047d %\047d %\047d\n",$1,$2,-$3,$2+$3}
			NR>n{printf "%s %\047d %\047d %\047d\n",$1,$2,$3,$2-$3}' |
		column -t |
		awk -v n=$nline 'BEGIN{print "---------------income---------------"}
			{print }
			NR==n{print "--------------spending--------------"}'
fi
