#!/bin/bash 

SD=~/.local/src/chogo
source ../.chogo

case $1 in
	cf) $SD/cf ${@:2};;
	bs)	$SD/bs ${@:2};;
	st) $SD/st ${@:2};;
	add) $SD/add ${@:2};;
	init) $SD/init ${@:2};;#TODO
	
	*) echo usage: $(basename $0) "[cf|bs|st|add|init]" >&2;;
esac
