#!/bin/bash 

SD=~/.local/src/chogo
export CG_DIR=..
export CG_CONF=$CG_DIR/conf
export accounts=$CG_CONF/accounts
export assets=$CG_CONF/assets
export liabilities=$CG_CONF/liabilities

case $1 in
	cf) $SD/cf ${@:2};;
	bs)	$SD/bs ${@:2};;
	st) $SD/st ${@:2};;
	add) $SD/add ${@:2};;
	bf) $SD/bf ${@:2};;
	init) $SD/init ${@:2};;#TODO
	
	*) echo usage: $(basename $0) "[cf|bs|st|add|init]" >&2;;
esac
